/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Mateo
 */
public class Vista_Reunion extends javax.swing.JInternalFrame {

    
    

    public JButton getBtnEliminar() {
        return BtnEliminar;
    }

    public void setBtnEliminar(JButton BtnEliminar) {
        this.BtnEliminar = BtnEliminar;
    }

    public JButton getBtnGuardar() {
        return BtnGuardar;
    }

    public void setBtnGuardar(JButton BtnGuardar) {
        this.BtnGuardar = BtnGuardar;
    }

    public JButton getBtnLimpiar() {
        return BtnLimpiar;
    }

    public void setBtnLimpiar(JButton BtnLimpiar) {
        this.BtnLimpiar = BtnLimpiar;
    }

    public JButton getBtnModificar() {
        return BtnModificar;
    }

    public void setBtnModificar(JButton BtnModificar) {
        this.BtnModificar = BtnModificar;
    }

    public JTable getJTdatos() {
        return JTdatos;
    }

    public void setJTdatos(JTable JTdatos) {
        this.JTdatos = JTdatos;
    }

    public JDateChooser getJdFecha() {
        return JdFecha;
    }

    public void setJdFecha(JDateChooser JdFecha) {
        this.JdFecha = JdFecha;
    }

    public JLabel getLblCodigo_reun() {
        return LblCodigo_reun;
    }

    public void setLblCodigo_reun(JLabel LblCodigo_reun) {
        this.LblCodigo_reun = LblCodigo_reun;
    }

    public JLabel getLblDuracion() {
        return LblDuracion;
    }

    public void setLblDuracion(JLabel LblDuracion) {
        this.LblDuracion = LblDuracion;
    }

    public JLabel getLblFecha() {
        return LblFecha;
    }

    public void setLblFecha(JLabel LblFecha) {
        this.LblFecha = LblFecha;
    }

    public JLabel getLblTopico() {
        return LblTopico;
    }

    public void setLblTopico(JLabel LblTopico) {
        this.LblTopico = LblTopico;
    }

    public JTextField getTxtCodReu() {
        return TxtCodReu;
    }

    public void setTxtCodReu(JTextField TxtCodReu) {
        this.TxtCodReu = TxtCodReu;
    }

    public JTextField getTxtDuracion() {
        return TxtDuracion;
    }

    public void setTxtDuracion(JTextField TxtDuracion) {
        this.TxtDuracion = TxtDuracion;
    }

    public JTextField getTxtTopic() {
        return TxtTopic;
    }

    public void setTxtTopic(JTextField TxtTopic) {
        this.TxtTopic = TxtTopic;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

   
    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JButton getBtn_Buscar_consult1() {
        return Btn_Buscar_consult1;
    }

    public void setBtn_Buscar_consult1(JButton Btn_Buscar_consult1) {
        this.Btn_Buscar_consult1 = Btn_Buscar_consult1;
    }

    public JDateChooser getjDcDesde1() {
        return jDcDesde1;
    }

    public void setjDcDesde1(JDateChooser jDcDesde1) {
        this.jDcDesde1 = jDcDesde1;
    }

    public JDateChooser getjDcHasta1() {
        return jDcHasta1;
    }

    public void setjDcHasta1(JDateChooser jDcHasta1) {
        this.jDcHasta1 = jDcHasta1;
    }

    public JLabel getLbldesde1() {
        return lbldesde1;
    }

    public void setLbldesde1(JLabel lbldesde1) {
        this.lbldesde1 = lbldesde1;
    }

    public JLabel getLblhasta1() {
        return lblhasta1;
    }

    public void setLblhasta1(JLabel lblhasta1) {
        this.lblhasta1 = lblhasta1;
    }

    
    /**
     * Creates new form Vista_Reunion
     */
    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public Vista_Reunion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblCodigo_reun = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        LblDuracion = new javax.swing.JLabel();
        LblTopico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTdatos = new javax.swing.JTable();
        BtnGuardar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        TxtCodReu = new javax.swing.JTextField();
        JdFecha = new com.toedter.calendar.JDateChooser();
        TxtDuracion = new javax.swing.JTextField();
        TxtTopic = new javax.swing.JTextField();
        jDcDesde1 = new com.toedter.calendar.JDateChooser();
        jDcHasta1 = new com.toedter.calendar.JDateChooser();
        Btn_Buscar_consult1 = new javax.swing.JButton();
        lblhasta1 = new javax.swing.JLabel();
        lbldesde1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reuniones");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reuniones.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 11, -1, -1));

        LblCodigo_reun.setForeground(new java.awt.Color(255, 255, 255));
        LblCodigo_reun.setText("Código:");
        getContentPane().add(LblCodigo_reun, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        LblFecha.setForeground(new java.awt.Color(255, 255, 255));
        LblFecha.setText("Fecha de la Reunion:");
        getContentPane().add(LblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        LblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        LblDuracion.setText("Duración estimada:");
        getContentPane().add(LblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        LblTopico.setForeground(new java.awt.Color(255, 255, 255));
        LblTopico.setText("Tòpico de la Reunion:");
        getContentPane().add(LblTopico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        JTdatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        JTdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "            Código", "           Fecha", "           Duración", "          Tópico"
            }
        ));
        JTdatos.setGridColor(new java.awt.Color(255, 153, 51));
        JTdatos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        JTdatos.setSelectionForeground(new java.awt.Color(0, 0, 51));
        jScrollPane1.setViewportView(JTdatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 630, 190));

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/vista_iconos/guardar.png"))); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 100, 40));

        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/vista_iconos/editar.png"))); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 100, 40));

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/vista_iconos/eliminar.png"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 100, 40));

        BtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/vista_iconos/limpiar.png"))); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 100, 40));
        getContentPane().add(TxtCodReu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, -1));
        getContentPane().add(JdFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 150, -1));
        getContentPane().add(TxtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 107, -1));
        getContentPane().add(TxtTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 107, -1));
        getContentPane().add(jDcDesde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 170, 20));
        getContentPane().add(jDcHasta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 170, -1));

        Btn_Buscar_consult1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/vista_iconos/consultar.png"))); // NOI18N
        Btn_Buscar_consult1.setText("Buscar");
        Btn_Buscar_consult1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(Btn_Buscar_consult1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 90, 40));

        lblhasta1.setForeground(new java.awt.Color(255, 255, 255));
        lblhasta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/vista_iconos/buscar.png"))); // NOI18N
        lblhasta1.setText("Consultar reunión hasta:");
        getContentPane().add(lblhasta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        lbldesde1.setForeground(new java.awt.Color(255, 255, 255));
        lbldesde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/vista_iconos/buscar.png"))); // NOI18N
        lbldesde1.setText("Consultar reunión desde:");
        getContentPane().add(lbldesde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/vista_imagenes/fondo_azul_oscuro.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton Btn_Buscar_consult1;
    private javax.swing.JTable JTdatos;
    private com.toedter.calendar.JDateChooser JdFecha;
    private javax.swing.JLabel LblCodigo_reun;
    private javax.swing.JLabel LblDuracion;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblTopico;
    private javax.swing.JTextField TxtCodReu;
    private javax.swing.JTextField TxtDuracion;
    private javax.swing.JTextField TxtTopic;
    private com.toedter.calendar.JDateChooser jDcDesde1;
    private com.toedter.calendar.JDateChooser jDcHasta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldesde1;
    private javax.swing.JLabel lblhasta1;
    // End of variables declaration//GEN-END:variables
}
